const ACTION_AUTH = {
  LOGIN: "@@LOGIN",
  REGISTRATION: "@@REGISTRATION",
  LOGOUT: "@@LOGOUT",
  CHECK_AUTH: "@@CHECK_AUTH",
  LOADING: "@@LOADING",
  SAVE_RESPONSE: "@@SAVE_RESPONSE",
  SAVE_CHECK_RESPONSE: "@@SAVE_CHECK_RESPONSE",
};

export default ACTION_AUTH;
